/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.NhapHangCtrl;
import Controller.NhapSachCtrl;
import Controller.XuatHangCtrl;
import FileHandler.PhieuNhapFileHandler;
import FileHandler.PhieuXuatFileHandler;
import FileHandler.SachFileHandler;
import Model.PhieuNhap;
import Model.PhieuXuat;
import Utils.AutoIdGenerator;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.RootPaneContainer;

/**
 *
 * @author Lo Dai Luc
 */
public class HomeFrm extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrm
     */
    private JPanel childPanel;

    public HomeFrm() {
        initComponents();
        this.setLocationRelativeTo(null);

//        //doc danh sach san pham
        NhapSachCtrl.getList().addAll(SachFileHandler.getInstance().readDaTaFromFile("sach.txt"));
        AutoIdGenerator.initializeCounterMaSach(NhapSachCtrl.getList());

//        //doc danh sach phieu nhap
        List<PhieuNhap> listPhieuNhap = new ArrayList<>(PhieuNhapFileHandler.getInstance().readDaTaFromFile("phieunhap.txt"));
        for (PhieuNhap phieuNhap : listPhieuNhap) {
            NhapHangCtrl.luuPhieuNhap(phieuNhap);
        }
        AutoIdGenerator.initializeCounterMaPhieuNhap(NhapHangCtrl.getList());

//        //doc danh sach phieu xuat
        List<PhieuXuat> listPhieuXuat = new ArrayList<>(PhieuXuatFileHandler.getInstance().readDaTaFromFile("phieuxuat.txt"));
        try {
            for (PhieuXuat phieuXuat : listPhieuXuat) {
                XuatHangCtrl.luuPhieuXuat(phieuXuat);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        AutoIdGenerator.initializeCounterMaPhieuXuat(XuatHangCtrl.getList());
        
        //demo xuất pdf, excel
//        PhieuNhapFileHandler.getInstance().exportPDF(NhapHangCtrl.getList().get(0));
//        PhieuXuatFileHandler.getInstance().exportPDF(XuatHangCtrl.getList().get(0));
//        SachFileHandler.getInstance().exportExcel(NhapSachCtrl.getList());
//        PhieuNhapFileHandler.getInstance().exportExcel(NhapHangCtrl.getList());
//        PhieuXuatFileHandler.getInstance().exportExcel(XuatHangCtrl.getList());

        childPanel = new NhapSanPham();
        MainContent.removeAll();
        MainContent.add(childPanel);
        MainContent.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNhapSanPham = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        btnPhieuNhap = new javax.swing.JButton();
        btnXuatHang = new javax.swing.JButton();
        btnPhieuXuat = new javax.swing.JButton();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNhapSanPham.setText("Nhập Sản Phẩm");
        btnNhapSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapSanPhamActionPerformed(evt);
            }
        });

        btnNhapHang.setText("Nhập Hàng");
        btnNhapHang.setPreferredSize(new java.awt.Dimension(160, 32));
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        btnPhieuNhap.setText("Phiếu Nhập");
        btnPhieuNhap.setPreferredSize(new java.awt.Dimension(160, 32));
        btnPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuNhapActionPerformed(evt);
            }
        });

        btnXuatHang.setText("Xuất Hàng");
        btnXuatHang.setPreferredSize(new java.awt.Dimension(160, 32));
        btnXuatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHangActionPerformed(evt);
            }
        });

        btnPhieuXuat.setText("Phiếu Xuất");
        btnPhieuXuat.setPreferredSize(new java.awt.Dimension(160, 32));
        btnPhieuXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnNhapSanPham)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNhapSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(btnPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(btnXuatHang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(btnPhieuXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        MainContent.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapSanPhamActionPerformed
        // TODO add your handling code here:
        childPanel = new NhapSanPham();
        MainContent.removeAll();
        MainContent.add(childPanel);
        MainContent.validate();
    }//GEN-LAST:event_btnNhapSanPhamActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        // TODO add your handling code here:
        childPanel = new NhapHang();
        MainContent.removeAll();
        MainContent.add(childPanel);
        MainContent.validate();
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void btnPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuNhapActionPerformed
        // TODO add your handling code here:
        childPanel = new PhieuNhapView();
        MainContent.removeAll();
        MainContent.add(childPanel);
        MainContent.validate();
    }//GEN-LAST:event_btnPhieuNhapActionPerformed

    private void btnXuatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHangActionPerformed
        // TODO add your handling code here:
        childPanel = new XuatHang();
        MainContent.removeAll();
        MainContent.add(childPanel);
        MainContent.validate();
    }//GEN-LAST:event_btnXuatHangActionPerformed

    private void btnPhieuXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuXuatActionPerformed
        // TODO add your handling code here:
        childPanel = new PhieuXuatView();
        MainContent.removeAll();
        MainContent.add(childPanel);
        MainContent.validate();
    }//GEN-LAST:event_btnPhieuXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainContent;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnNhapSanPham;
    private javax.swing.JButton btnPhieuNhap;
    private javax.swing.JButton btnPhieuXuat;
    private javax.swing.JButton btnXuatHang;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
