/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import FileHandler.PhieuNhapFileHandler;
import Model.ChiTietPhieu;
import Model.PhieuNhap;
import Utils.NumberUtils;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import Model.Phieu;

/**
 *
 * @author Lo Dai Luc
 */
public class XemChiTietPhieuNhap extends javax.swing.JDialog implements View {

    /**
     * Creates new form XemChiTietPhieu
     */
    private PhieuNhapView parent;
    private DefaultTableModel modelPhieu;
    private PhieuNhap phieunhap;
    
    public XemChiTietPhieuNhap(javax.swing.JPanel parent, javax.swing.JFrame owner, boolean modal, Phieu phieu) {
        super(owner, modal);
        initComponents();
        this.parent = (PhieuNhapView) parent;
        this.setLocationRelativeTo(null);

        modelPhieu = (DefaultTableModel) tblChiTiet.getModel();
        initTablePhieu(modelPhieu);

        txtMaPhieu.setText(phieu.getMaPhieu());
        phieunhap = (PhieuNhap) phieu;
        txtNhaCungCap.setText(phieunhap.getNhaCungCap());
        txtThoiGianTao.setText(phieunhap.getThoiGianTao());

        showData(phieunhap.getCTPhieu(), modelPhieu);
        txtTongThanhToan.setText(TongThanhToan(modelPhieu));
    }

    private XemChiTietPhieuNhap(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public final void initTablePhieu(DefaultTableModel modelPhieuNhap) {
        String[] headerTbl = new String[]{"STT", "Mã sách", "Tên sách", "Số lượng", "Đơn giá", "Thành tiền"};
        modelPhieuNhap.setColumnIdentifiers(headerTbl);
        tblChiTiet.setModel(modelPhieuNhap);

        tblChiTiet.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblChiTiet.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblChiTiet.getColumnModel().getColumn(2).setPreferredWidth(200);
        tblChiTiet.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblChiTiet.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblChiTiet.getColumnModel().getColumn(5).setPreferredWidth(100);

        tblChiTiet.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    public String TongThanhToan(DefaultTableModel modelPhieu) {
        int col = 5; // Cột thành tiền

        double tong = 0;
        for (int row = 0; row < modelPhieu.getRowCount(); row++) {
            String valueText = (String) modelPhieu.getValueAt(row, col);
            valueText = NumberUtils.extractDigits(valueText);
            double value = Double.parseDouble(valueText);
            tong += value;
        }
        return NumberUtils.formatCurrency(tong);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaPhieu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNhaCungCap = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtThoiGianTao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTongThanhToan = new javax.swing.JLabel();
        btnXuatPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã phiếu:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Chi Tiết Phiếu Nhập");

        txtMaPhieu.setText("jLabel5");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nhà cung cấp: ");

        txtNhaCungCap.setText("jLabel6");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Thời gian tạo:");

        txtThoiGianTao.setText("jLabel7");

        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sách", "Tên sách", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tblChiTiet);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tổng thanh toán:");

        txtTongThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTongThanhToan.setText("jLabel6");

        btnXuatPDF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatPDF.setText("Xuất PDF");
        btnXuatPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(txtThoiGianTao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXuatPDF)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtMaPhieu)
                    .addComponent(txtThoiGianTao))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNhaCungCap))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongThanhToan)
                    .addComponent(btnXuatPDF))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatPDFActionPerformed
        // TODO add your handling code here:
        PhieuNhapFileHandler.getInstance().exportPDF(phieunhap);
    }//GEN-LAST:event_btnXuatPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                XemChiTietPhieuNhap dialog = new XemChiTietPhieuNhap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChiTiet;
    private javax.swing.JLabel txtMaPhieu;
    private javax.swing.JLabel txtNhaCungCap;
    private javax.swing.JLabel txtThoiGianTao;
    private javax.swing.JLabel txtTongThanhToan;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        int n = 1;
        for (T t : list) {
            if (t instanceof ChiTietPhieu) {
                ChiTietPhieu cTP = (ChiTietPhieu) t;
                model.addRow(new Object[]{
                    n++, cTP.getMaSach(), cTP.getTenSach(), cTP.getSoLuong(),
                    NumberUtils.formatCurrency(cTP.getDonGia()), NumberUtils.formatCurrency(cTP.getDonGia() * cTP.getSoLuong())
                });
            }
        }
    }
}
